#
# Add default properties here!
#

########################################################################################################################
## SPRING ##############################################################################################################
########################################################################################################################

server.port: 9903
spring.application.name: messages-v1
