version: '3'
services:
  ui:
    build: ui/.
    ports:
      - "9800:80"
  eureka:
    build: eureka/.
    ports:
      - "9901:9901"
    environment:
      - "SPRING_PROFILES_ACTIVE=default,prod"
    depends_on:
      - ui
  zuul:
    build: zuul/.
    ports:
      - "9900:9900"
    environment:
      - "SPRING_PROFILES_ACTIVE=default,prod"
    depends_on:
      - eureka
  users:
    build: users/.
    ports:
      - "9902:9902"
    environment:
      - "SPRING_PROFILES_ACTIVE=default,prod"
    depends_on:
      - zuul
  messages:
    build: messages/.
    ports:
      - "9903:9903"
    environment:
      - "SPRING_PROFILES_ACTIVE=default,prod"
    depends_on:
      - users
  tawks:
    build: tawks/.
    ports:
      - "9904:9904"
    environment:
      - "SPRING_PROFILES_ACTIVE=default,prod"
    depends_on:
      - messages
