version: '3'
services:
  zuul:
    build: zuul/.
    ports:
      - "9900:9900"
    environment:
      - "SPRING_PROFILES_ACTIVE=default,prod"
    depends_on:
      - eureka
  eureka:
    build: eureka/.
    ports:
      - "9901:9901"
    environment:
      - "SPRING_PROFILES_ACTIVE=default,prod"
  users:
    build: users/.
    ports:
      - "9902:9902"
    environment:
      - "SPRING_PROFILES_ACTIVE=default,prod"
    depends_on:
      - eureka
  messages:
    build: messages/.
    ports:
      - "9903:9903"
    environment:
      - "SPRING_PROFILES_ACTIVE=default,prod"
    depends_on:
      - eureka
  tawks:
    build: tawks/.
    ports:
      - "9904:9904"
    environment:
      - "SPRING_PROFILES_ACTIVE=default,prod"
    depends_on:
      - eureka
