#
# Add default properties here!
#

########################################################################################################################
## SPRING ##############################################################################################################
########################################################################################################################

server.port: 9002
spring.profiles.active: default,local
spring.application.name: users-v1

########################################################################################################################
## EUREKA ##############################################################################################################
########################################################################################################################

eureka.client.serviceUrl.defaultZone: http://localhost:9001/eureka
eureka.client.register-with-eureka: true
eureka.client.fetch-registry: true

logging.level.com.netflix.eureka: 'OFF'
logging.level.com.netflix.discovery: 'OFF'