#
# Add PROD properties here!
#

########################################################################################################################
## EUREKA ##############################################################################################################
########################################################################################################################

eureka.client.serviceUrl.defaultZone: http://eureka:9901/eureka
eureka.client.register-with-eureka: true
eureka.client.fetch-registry: true
eureka.client.healthcheck.enabled: true

logging.level.com.netflix.eureka: 'OFF'
logging.level.com.netflix.discovery: 'OFF'
