#
# Add default properties here!
#

########################################################################################################################
## SPRING ##############################################################################################################
########################################################################################################################

server.port: 9902
spring.application.name: users-v1
