#
# Add default properties here!
#

########################################################################################################################
## SPRING ##############################################################################################################
########################################################################################################################

server.port: 9001
spring.profiles.active: default,local
spring.application.name: eureka-v1

########################################################################################################################
## EUREKA ##############################################################################################################
########################################################################################################################

eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false

logging.level.com.netflix.eureka: 'OFF'
logging.level.com.netflix.discovery: 'OFF'
