#
# Add default properties here!
#

########################################################################################################################
## SPRING ##############################################################################################################
########################################################################################################################

server.port: 9901
spring.application.name: eureka-v1
